Added 3rd endpoint
qmk/v-usb pull request #1
Opened 2020-05-05 00:04 UTC by yiancar

- Added 3rd endpoint check in asmcommon. This adds 2 extra cycles to the USB routine when enabled. With 16MHz clock (most if not all qmk build use that) the routine is still within spec.

- Updated prototype.h file to add additional options.

- Simulatanius changes in QMK to follow soon

2020-05-05 02:34 UTC, fauxpark commented
I'm pretty sure all of the PS2AVRGB boards (the majority of V-USB boards) run at 12MHz.

2020-05-05 02:37 UTC, yiancar commented
Interesting, Sorry I was unaware. Could you try with some if you have any and report results. Maybe A good way is to add a warning if 3 endpoints are used at the same time. In theory disabling the 3rd endpoint should take you back to the way everything was before.

2020-05-18 18:51 UTC, yiancar commented
Ok Back for more:
This has now been tested at 12MHz and 16MHz and works as expected.
Complimentary PR at future branch can verify this.

2020-05-19 01:23 UTC, fauxpark requested changes

2020-05-19 01:23 UTC, fauxpark commented on usbdrv/usbdrvasm.S
> +#else  /* __IAR_SYSTEMS_ASM__ */
```suggestion
#else  /* __IAR_SYSTEMS_ASM__ */ 
```

2020-05-19 01:23 UTC, fauxpark commented on usbdrv/usbdrvasm.S
> +;
```suggestion
; 
```

2020-05-19 01:23 UTC, fauxpark commented on usbdrv/usbdrvasm.S
> +;
```suggestion
; 
```

2020-05-19 01:23 UTC, fauxpark commented on usbdrv/usbdrvasm.S
> +#else  /* __IAR_SYSTEMS_ASM__ */
```suggestion
#else  /* __IAR_SYSTEMS_ASM__ */ 
```

2020-05-19 01:23 UTC, fauxpark commented on usbdrv/usbdrv.c
>      18 + 7 * USB_CFG_HAVE_INTRIN_ENDPOINT + 7 * USB_CFG_HAVE_INTRIN_ENDPOINT3 +
```suggestion
    18 + 7 * USB_CFG_HAVE_INTRIN_ENDPOINT + 7 * USB_CFG_HAVE_INTRIN_ENDPOINT3 + 7 * USB_CFG_HAVE_INTRIN_ENDPOINT4 +
```

2020-05-19 01:23 UTC, fauxpark commented on usbdrv/usbdrv.c
> +         7 * USB_CFG_HAVE_INTRIN_ENDPOINT4 +(USB_CFG_DESCR_PROPS_HID & 0xff), 0,
```suggestion
                (USB_CFG_DESCR_PROPS_HID & 0xff), 0,
```

2020-05-19 01:23 UTC, fauxpark commented on usbdrv/usbdrv.c
> +#if USB_CFG_HAVE_INTRIN_ENDPOINT4   /* endpoint descriptor for endpoint 3 */
```suggestion
#if USB_CFG_HAVE_INTRIN_ENDPOINT4   /* endpoint descriptor for endpoint 4 */
```

2020-05-19 01:23 UTC, fauxpark commented on usbdrv/usbdrv.c
> +    (char)(0x80 | USB_CFG_EP4_NUMBER), /* IN endpoint number 3 */
```suggestion
    (char)(0x80 | USB_CFG_EP4_NUMBER), /* IN endpoint number 4 */
```

2020-06-02 00:24 UTC, yiancar commented
@fauxpark @jackhumbert apparently this needs permissions etc to be reviewed:)

2020-08-05 17:13 UTC, fauxpark approved these changes
Tested on my wonky JJ4x4, can't say anything about larger boards but works like a charm! Nice work @yiancar 👍

2020-08-16 00:06 UTC, noroadsleft approved these changes
`__attribute__ ((weak))` :heavy_check_mark:

2020-08-16 00:07 UTC, merged

2020-08-16 00:07 UTC, noroadsleft commented
Thanks!